# https://blog.callr.tech/building-docker-images-with-gitlab-ci-best-practices/

stages:
  - build
  - deploy-image
  - deploy-cloudrun
  - build-production
  - deploy-image-production
  - deploy-cloudrun-production

default:
  image: docker:19

variables:
  DOCKER_BUILDKIT: 1

before_script:
  # docker login asks for the password to be passed through stdin for security
  # we use $CI_JOB_TOKEN here which is a special token provided by GitLab
  - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  - cat $GOOGLE_SA | docker login -u _json_key --password-stdin https://us-docker.pkg.dev

.build:
  stage: build
  script:
    - cp $dotEnv .env
    # fetches the latest image (not failing if image is not found)
    - docker pull $CI_REGISTRY_IMAGE/$CI_ENVIRONMENT_SLUG:latest || true
    # builds the project, passing proxy variables, and vcs vars for LABEL
    # notice the cache-from, which is going to use the image we just pulled locally
    # the built image is tagged locally with the commit SHA, and then pushed to
    # the GitLab registry
    - >
      docker build
      --pull
      --cache-from $CI_REGISTRY_IMAGE/$CI_ENVIRONMENT_SLUG:latest
      --tag $CI_REGISTRY_IMAGE/$CI_ENVIRONMENT_SLUG:latest
      --tag $CI_REGISTRY_IMAGE/$CI_ENVIRONMENT_SLUG:$CI_COMMIT_SHA
      .
    - docker push $CI_REGISTRY_IMAGE/$CI_ENVIRONMENT_SLUG:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE/$CI_ENVIRONMENT_SLUG:latest

build-dev:
  extends: .build
  environment: dev
  only:
    - development

build-staging:
  extends: .build
  environment: dev-staging
  only:
    - main

build-production:
  extends: .build
  stage: build-production
  environment: production
  only:
    - main

.deploy-to-gar:
  stage: deploy-image
  script:
    # fetch the image
    - docker pull $CI_REGISTRY_IMAGE/$CI_ENVIRONMENT_SLUG:$CI_COMMIT_SHA
    # tag and push to Artifact Registry
    - docker tag $CI_REGISTRY_IMAGE/$CI_ENVIRONMENT_SLUG:$CI_COMMIT_SHA $GAR_REPO:latest
    - docker push $GAR_REPO:latest

deploy-to-gar-dev:
  extends: .deploy-to-gar
  environment: dev
  only:
    - development

deploy-to-gar-staging:
  extends: .deploy-to-gar
  environment: dev-staging
  only:
    - main

deploy-to-gar-production:
  extends: .deploy-to-gar
  stage: deploy-image-production
  environment: production
  when: manual
  allow_failure: false
  only:
    - main

.deploy-to-cloudrun:
  stage: deploy-cloudrun
  image: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
  variables:
    SlackTemplate: >-
        $CI_ENVIRONMENT_URL deployed by ${GITLAB_USER_NAME}'s <$CI_PIPELINE_URL|pipeline> on
        branch <$CI_PROJECT_URL/-/commits/$CI_COMMIT_REF_NAME|$CI_COMMIT_REF_NAME>
        of <$CI_PROJECT_URL/-/tree/$CI_COMMIT_REF_NAME|$CI_PROJECT_PATH>.

        Commit message: <${CI_PROJECT_URL}/commit/${CI_COMMIT_SHA}|$CI_COMMIT_SHORT_SHA> ${CI_COMMIT_MESSAGE}
  before_script: []
  script:
    - gcloud auth activate-service-account --key-file=$GOOGLE_SA
    - gcloud --project=$GCP_PROJECT run deploy $CloudRun_Service --region=us-east1 --image $GAR_REPO:latest --ingress=internal-and-cloud-load-balancing
    - >-
        curl -sS -X POST "https://api.cloudflare.com/client/v4/zones/$CF_Zone/purge_cache" \
          -H "Authorization: Bearer $CF_Token" -H "Content-Type:application/json" \
          --data '{"hosts": ["'$CF_Host'"]}'
    - apk add --no-cache jq
    - >-
        jq -n --arg msg "$SlackTemplate" '{text: $msg}'
        |
        curl -sS -o - -X POST -H 'Content-type: application/json'
        --data @-
        $SlackWebhook

deploy-to-cloudrun-dev:
  extends: .deploy-to-cloudrun
  environment: dev
  only:
    - development

deploy-to-cloudrun-staging:
  extends: .deploy-to-cloudrun
  environment: dev-staging
  only:
    - main

deploy-to-cloudrun-production:
  extends: .deploy-to-cloudrun
  stage: deploy-cloudrun-production
  environment: production
  only:
    - main
