import React from 'react';
import { Inter } from 'next/font/google';

import '@/styles/globals.css';
import PrimaryButton from '@/components/Buttons/primary';
import LogoSvg from '@/assets/svg/logo';
import Footer from '@/components/Footer';
import styles from './layout.module.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ fontSize: '10px' }}>
        <header className={styles.header}>
          <div className={styles.labelWrapper}>
            <LogoSvg />
            <p className={styles.label}>Planes Live</p>
          </div>
          <PrimaryButton>Download app</PrimaryButton>
        </header>
        {children}
        <Footer />
      </body>
    </html>
  );
}
